site_name: RCAC Documentation
site_description: RCAC Blogs written by scientists.
site_url: https://rcac-blogs.readthedocs.io

theme:
  name: material
  logo: assets/purdue.png
  favicon: assets/purdue_favicon.png
  custom_dir: overrides
  font:
    text: Roboto
    code: Consolas
  features:
    - navigation.indexes
    # Back-to-top button¶
    - navigation.top
    - navigation.footer
    #  - navigation.sections
    #  - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight
    #- search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      post_date_format: long
      categories_allowed:
        - Anvil
        - Software
        - Slurm
      pagination_per_page: 5
      pagination_if_single_page: true
  - tags:
      enabled: true
  - git-revision-date-localized:
      enable_creation_date: true
  - macros

nav:
  - Home: index.md
  - HPC User Guides:
    - Anvil User Guide: 
      - userguides/anvil/index.md
      - Anvil Overview: userguides/anvil/overview.md
      - Accessing the System: userguides/anvil/access.md
      - System Architecture: userguides/anvil/system.md
    - Gautschi User Guide:
      - userguides/gautschi/index.md
      - Biography of Gautschi: userguides/gautschi/biography.md
      - Gautschi Overview: userguides/gautschi/overview.md
  - RCAC Blogs:
    - blog/index.md
    #- Tags: blog/tags.md
  - RCAC Tags: tags.md
  - Templates and Notes: notes.md

extra:
  social:
  - icon: /fontawesome/regular/envelope
    name: Get additional help from rcac-help
    link: mailto:<rcac-help@purdue.edu>
  - icon: fontawesome/brands/github
    name: Check RCAC public GitHub page
    link: https://github.com/PurdueRCAC
  - icon: fontawesome/brands/x-twitter
    name: Follow RCAC on X
    link: https://x.com/PurdueRCAC
  - icon: fontawesome/brands/discord
    name: Join our Purdue RCD Community Discord channel
    link: https://discord.gg/RmtKZmaQW9
  - icon: /material/mailbox
    name: contact us
    link: /contact
  org: Rosen Center for Advanced Computing
  analytics:
    provider: google
    property: G-3D80JBWGP0  # Guangzhen's Google Analytics
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/Guangzhen-Jin/rcac-blogs/issues/new" target="_blank" rel="noopener">feedback form</a>.

features:
  - search.suggest
  - search.highlight
  - search.share
  - navigation.top
  - navigation.tabs

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
# # Adding share buttons
# hooks:
#   - hooks/socialmedia.py

# Copyright
copyright: Copyright &copy; 2025 Rosen Center for Advanced Computing