authors:
  team:
    name: Team
    description: Creator
    avatar: https://simpleicons.org/icons/materialformkdocs.svg
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
  jin456:
    name: Guangzhen Jin
    description: Senior Computational Scientist
    avatar: https://www.rcac.purdue.edu/files/users/jin456/photo.jpg
    slug: https://www.rcac.purdue.edu/about/staff/jin456
    url: https://www.rcac.purdue.edu/about/staff/jin456